import { IDENTITY_LIMITS, IMAGE_INTERVAL } from '@shared/identity';
import { CTA_COPY } from '../../lib/cta';
import { ICON_PICKER_COPY } from '../../lib/iconPicker';
import { REORDER_LABELS } from '../../lib/reorder';

/** Identity page (Figma 538:8099 Labels & CTAs, 546:12416 Display options). */
export const IDENTITY = {
  eyebrow: 'Portfolio workspace',
  title: 'Identity',
  subtitle: 'Manage the personal details and media that introduce you across the site.',

  error: {
    title: 'Could not load your identity',
    message: 'Something went wrong while loading your hero and profile details.',
    retry: 'Try again',
  },

  save: {
    saved: { title: 'All changes saved', text: 'Changes are saved automatically to your draft' },
    pending: { title: 'Saving…', text: 'Your draft is being saved' },
    invalid: { title: 'Not saved yet', text: 'Fix the highlighted fields and your draft saves again' },
    blocked: { title: 'Not saved yet', text: 'Confirm the title change to keep saving' },
    error: { title: 'Could not save your draft', text: 'Check your connection and try again' },
    retry: 'Retry',
    complete: 'Identity complete',
    completeLabel: (percent) => `Identity ${percent}% complete`,
    leaveWarning: 'Your latest changes are not saved yet.',
  },

  basic: {
    title: 'Basic info',
    description: 'The personal details shown across your hero and footer.',
    displayName: { label: 'Display name', hint: 'The large name behind your hero photo.', placeholder: 'Youssef Ramadan' },
    role: { label: 'Professional title / role', hint: 'Used in the hero pill.', placeholder: 'Backend Software Engineer' },
  },

  tabs: {
    label: 'Hero content',
    labels: 'Labels & CTAs',
    images: 'Headline images',
    display: 'Display options',
  },

  labels: {
    title: { label: 'Title', placeholder: 'I Design Experience Not Just Screens' },
    words: 'Words:',
    wordImage: 'has an image spot after it',
    wordBreak: 'has a line break after it',
    description: { label: 'Subtitle / description', optional: 'Optional', placeholder: 'A short line about what you do.' },
    ctas: 'Calls to action',
    primary: 'Primary CTA',
    secondary: 'Secondary CTA',
    ...CTA_COPY,
    section: { label: 'Section', placeholder: 'Choose a section' },
    cvInfo: 'Opens the resume uploaded below.',
    cvMissing: 'Upload a resume below, or this button stays hidden on the site.',
  },

  orphans: {
    title: 'Remove image spots?',
    description: 'You changed the title, so some image spots or the line break no longer have a word to follow.',
    slot: (word, count) => `Image spot after “${word}” (${count} ${count === 1 ? 'image' : 'images'})`,
    lineBreak: (word) => `Line break after “${word}”`,
    lineBreakLast: 'The line break would come after the last word',
    confirm: 'Remove and keep title',
    cancel: 'Undo title change',
  },

  images: {
    intro: 'Choose where images appear between the words of your title. Each spot shows its images one after another.',
    empty: 'Write a title in Labels & CTAs first.',
    interval: {
      label: 'Time per image',
      unit: 'seconds',
      hint: `How long each image stays before the next one (${IMAGE_INTERVAL.min} to ${IMAGE_INTERVAL.max} seconds).`,
    },
    gapLabel: (word) => `Options after “${word}”`,
    addSpot: 'Add image spot here',
    removeSpot: 'Remove image spot',
    addBreak: 'Start a new line here',
    removeBreak: 'Remove line break',
    maxSpots: `Up to ${IDENTITY_LIMITS.imageSlots} image spots`,
    lineBreakBadge: 'Line break',
    spotBadge: (number) => `Spot ${number}`,
    spotTitle: (number, word) => `Spot ${number} · after “${word}”`,
    tilt: (number) => (number % 2 ? 'Tilts right' : 'Tilts left'),
    count: (count) => `${count}/${IDENTITY_LIMITS.slotImages}`,
    noImages: 'No images yet. Add at least one, or remove this spot before publishing.',
    addImages: 'Choose media',
    upload: 'Upload',
    uploading: (progress) => `Uploading ${progress}%`,
    full: `This spot is full (${IDENTITY_LIMITS.slotImages} images).`,
    removeImage: (index) => `Remove image ${index}`,
    moveImage: (index) => `Reorder image ${index}`,
    imageLabel: (index) => `Image ${index}`,
    deleteSpot: 'Remove spot',
    deleteSpotTitle: 'Remove this image spot?',
    deleteSpotText: (word) => `The images after “${word}” disappear from your title. They stay in your media library.`,
    deleteSpotConfirm: 'Remove spot',
    cancel: 'Cancel',
    ...REORDER_LABELS,
  },

  display: {
    intro: 'Keep section-specific controls minimal so the template remains consistent.',
    skillTags: { label: 'Floating capability tags', text: 'Small tags floating next to your hero photo' },
    stats: { label: 'Highlights / stats', text: 'Small proof points displayed near the hero' },
    highlights: {
      title: 'Highlights',
      text: `Up to ${IDENTITY_LIMITS.stats} proof points, e.g. “5+ Years experience”.`,
      add: 'Add highlight',
      max: `You can show up to ${IDENTITY_LIMITS.stats} highlights.`,
      value: 'Value',
      valuePlaceholder: '5+',
      titleLabel: 'Title',
      titlePlaceholder: 'Years experience',
      pill: 'Pill',
      pillPlaceholder: 'Pill (optional)',
      remove: (index) => `Remove highlight ${index}`,
      move: (index) => `Reorder highlight ${index}`,
      itemLabel: (index) => `Highlight ${index}`,
      empty: 'No highlights yet.',
    },
    tags: {
      title: 'Capability tags',
      text: 'Pick an icon and a short name for each tag.',
      add: 'Add capability tag',
      label: 'Name',
      placeholder: 'UX Thinking',
      icon: 'Icon',
      remove: (index) => `Remove capability tag ${index}`,
      move: (index) => `Reorder capability tag ${index}`,
      itemLabel: (index) => `Capability tag ${index}`,
      empty: 'No capability tags yet.',
    },
    iconPicker: ICON_PICKER_COPY,
    hiddenNote: 'Hidden on the site. You can still edit them.',
    ...REORDER_LABELS,
  },

  visuals: {
    title: 'Visuals',
    description: 'Upload new media here or pick an existing asset from your library.',
    portrait: { label: 'Portrait', hint: 'Primary hero photo', empty: 'No portrait yet', upload: 'Upload new' },
    logo: { label: 'Logo / mark', hint: 'Used in nav and footer', fallback: 'Initial fallback is active', upload: 'Upload logo' },
    inUse: 'In use',
    choose: 'Choose media',
    uploading: (progress) => `Uploading ${progress}%`,
    alt: { label: 'Alt text', optional: 'Optional', placeholder: 'Youssef Ramadan in a suit' },
    cursor: {
      label: 'Cursor name',
      optional: 'Optional',
      hint: 'Shown next to the mouse over your photo, like a Figma cursor. Leave empty to hide it.',
      placeholder: 'Youssef Ramadan',
      color: 'Cursor',
      background: 'Name tag',
      colorHex: (name) => `${name} color (hex)`,
    },
  },

  resume: {
    title: 'Resume',
    description: 'This file is downloaded from the Download CV action in your navigation.',
    empty: 'No resume uploaded yet',
    emptyText: 'PDF up to 10 MB',
    meta: (size) => `PDF · ${size}`,
    upload: 'Upload PDF',
    choose: 'Choose media',
    replace: 'Replace',
    uploading: (progress) => `Uploading ${progress}%`,
    open: 'Open',
    remove: 'Remove resume',
    removeTitle: 'Remove your resume?',
    removeText: 'Download CV buttons are hidden on the site until you add a new one. The file stays in your media library.',
    removeConfirm: 'Remove',
    cancel: 'Cancel',
  },

  preview: {
    eyebrow: 'Live content preview',
    title: 'Hero identity',
    draft: 'Draft',
    live: 'Live',
    note: 'Shows your draft. Visitors see the published version until you publish.',
    portraitAlt: 'Portrait preview',
    changes: (count) => `${count} unpublished ${count === 1 ? 'change' : 'changes'}`,
    upToDate: 'Everything is published',
    upToDateText: 'Your site shows the latest version.',
    publish: 'Publish changes',
    publishing: 'Publishing…',
    waiting: 'Waiting for your draft to save…',
    discard: 'Discard',
    discardTitle: 'Discard your changes?',
    discardText: 'Your draft goes back to the version that is live on the site. This cannot be undone.',
    discardConfirm: 'Discard changes',
    discarding: 'Discarding…',
    cancel: 'Keep editing',
    publishError: 'Could not publish your changes.',
    discardError: 'Could not discard your changes. Please try again.',
    published: 'Published. Your site now shows these changes.',
  },

  /** Names of the changed fields under "N unpublished changes". */
  fields: {
    displayName: 'Display name',
    role: 'Role',
    title: 'Title',
    description: 'Description',
    lineBreak: 'Line break',
    imageSlots: 'Headline images',
    imageInterval: 'Time per image',
    ctaPrimary: 'Primary CTA',
    ctaSecondary: 'Secondary CTA',
    photo: 'Portrait',
    photoCursor: 'Photo cursor',
    logo: 'Logo',
    cv: 'Resume',
    showSkillTags: 'Capability tags switch',
    skillTags: 'Capability tags',
    showStats: 'Highlights switch',
    stats: 'Highlights',
  },

  validation: {
    tooLong: (max) => `Use ${max} characters or fewer`,
    url: 'Enter a valid URL, e.g. https://dribbble.com/you',
    statValue: 'Use a number with an optional suffix, e.g. 5+ or 100%',
    interval: `Use ${IMAGE_INTERVAL.min} to ${IMAGE_INTERVAL.max} seconds`,
    color: 'Use a hex color, e.g. #35d0ba',
  },
};